import { useState, FormEvent } from "react";
import Link from "next/link";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";

export default function ImageGenerator() {
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async (e: FormEvent) => {
    e.preventDefault();
    if (!prompt.trim() || loading) return;

    setLoading(true);
    setError(null);
    setImageUrl(null);

    try {
      const res = await fetch("/api/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim() }),
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "Failed to generate image");
      }
      setImageUrl(data.imageUrl);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-white text-gray-900 p-4 md:p-8">
      <div className="max-w-3xl mx-auto py-8">
        <Link href="/" className="text-blue-600 underline text-sm">
          &larr; Back to Home
        </Link>

        <h1 className="text-3xl md:text-4xl font-bold mt-6 mb-2">
          AI Image Generator
        </h1>
        <p className="text-gray-700 mb-8">
          Powered by Nano Banana Pro. Describe an image and we&apos;ll generate
          it for you.
        </p>

        <Card>
          <CardContent className="p-6">
            <form onSubmit={handleGenerate} className="space-y-4">
              <label htmlFor="prompt" className="block font-medium text-gray-900">
                Image Prompt
              </label>
              <input
                id="prompt"
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="A sunset over a calm ocean with sailboats..."
                className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none"
              />
              <Button
                type="submit"
                disabled={!prompt.trim() || loading}
                className="text-base px-6 py-3 rounded-2xl shadow-md w-full md:w-auto"
              >
                {loading ? "Generating..." : "Generate Image"}
              </Button>
            </form>

            {error && (
              <p className="mt-4 text-red-600 text-sm">{error}</p>
            )}
          </CardContent>
        </Card>

        {loading && (
          <div className="mt-8 text-center text-gray-500">
            <div className="inline-block w-8 h-8 border-4 border-gray-300 border-t-blue-600 rounded-full animate-spin"></div>
            <p className="mt-2">Generating your image...</p>
          </div>
        )}

        {imageUrl && (
          <div className="mt-8">
            <img
              src={imageUrl}
              alt={prompt}
              className="w-full rounded-xl shadow-lg"
            />
          </div>
        )}

        <p className="mt-8 text-xs text-gray-500">
          Images are generated by AI and may not be perfectly accurate. All
          generated images include a SynthID watermark.
        </p>
      </div>
    </div>
  );
}
